package main

const (
	RPL_WELCOME  = "001"
	RPL_YOURHOST = "002"
	RPL_CREATED  = "003"
	RPL_MYINFO   = "004"
	RPL_ISUPPORT = "005"
)

const (
	ERR_UNKNOWNCOMMAND    = "421"
	ERR_INPUTTOOLONG      = "417"
	ERR_NEEDMOREPARAMS    = "461"
	ERR_NICKNAMEINUSE     = "433"
	ERR_ALREADYREGISTERED = "462"
)
